# This is the build workflow for GitHub Actions.

name: Build
on:
  pull_request:
  push:
    branches:
      - "**"
  workflow_call:
    inputs:
      ref:
        required: false
        type: string

permissions:
  id-token: write
  contents: read
  attestations: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        if: ${{ inputs.ref == '' }}
        uses: actions/checkout@v4.1.7
      - name: Checkout requested ref
        if: ${{ inputs.ref != '' }}
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ inputs.ref }}
      - uses: gradle/actions/wrapper-validation@v3.5.0
      - name: Setup JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: temurin
      - name: Mark gradlew as an executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Determine artifact name
        id: name
        run: |
          BASE_NAME=$(awk -F '=' '/archives_base_name/ { print $2; }' gradle.properties)
          VERSION=$(awk -F '=' '/mod_version/ { print $2; }' gradle.properties)
          echo "name=$BASE_NAME-$VERSION.jar" >> $GITHUB_OUTPUT
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1.3.2
        with:
          subject-path: build/libs/${{ steps.name.outputs.name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: Artifacts
          path: build/libs/${{ steps.name.outputs.name }}
