# This is the build workflow for GitHub Actions.

name: Build
on:
  push:
    pull_request:
    push:
      branches:
        - "**"
    workflow_call:
      inputs:
        ref:
          required: false
          type: string

permissions:
  id-token: write
  contents: read
  attestations: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        if: ${{ inputs.ref == '' }}
        uses: actions/checkout@v3.5.2
      - name: Checkout requested ref
        if: ${{ inputs.ref != '' }}
        uses: actions/checkout@v3.5.2
        with:
          ref: ${{ inputs.ref }}
      - uses: gradle/wrapper-validation-action@v1.0.4
      - name: Setup JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          java-version: 17
          distribution: temurin
      - name: Mark gradlew as an executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Read gradle.properties
        uses: madhead/read-java-properties@2.0.3
        id: properties
        with:
          file: gradle.properties
          all: true
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1.3.2
        with:
          subject-path: build/libs/${{ steps.properties.outputs.archives_base_name }}-${{ steps.properties.outputs.mod_version }}.jar
      - name: Upload artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Artifacts
          path: build/libs/${{ steps.properties.outputs.archives_base_name }}-${{ steps.properties.outputs.mod_version }}.jar
